#ifndef _ERROR_DEF_H
#define _ERROR_DEF_H

typedef enum {
    UNKNOWN_OPERATION,
    MOVE_SUCCESS,
    POS_OUT_OF_BOUND,
    WRONG_PLAYER,
    DOUBLE_CHESS_MOVED_LAST_TIME,
    NOT_DOUBLE_CHESS,
    HAS_CHESS,
    UP_HAS_OBSTACLE,
    DOWN_HAS_OBSTACLE,
    LEFT_HAS_OBSTACLE,
    RIGHT_HAS_OBSTACLE,
    UP_LEFT_HAS_OBSTACLE,
    UP_RIGHT_HAS_OBSTACLE,
    DOWN_LEFT_HAS_OBSTACLE,
    DOWN_RIGHT_HAS_OBSTACLE,
    OUT_OF_UP_BOUND,
    OUT_OF_DOWN_BOUND,
    OUT_OF_LEFT_BOUND,
    OUT_OF_RIGHT_BOUND,
    OUT_OF_UP_LEFT_BOUND,
    OUT_OF_UP_RIGHT_BOUND,
    OUT_OF_DOWN_LEFT_BOUND,
    OUT_OF_DOWN_RIGHT_BOUND,
} MoveError;

typedef enum {
    NO_AVAILABLE_CHOICE,
    ROBOT_SUCCESS,
} RobotError;

#endif
